# Stage 1: Setup and dependency installation
FROM lmsysorg/sglang:v0.4.9.post6-cu126 AS builder

WORKDIR /code

# Install base packages and Python
RUN apt-get update && \
    apt-get install -y \
        fonts-noto-core \
        fonts-noto-cjk \
        fontconfig \
        libgl1 && \
    fc-cache -fv && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install -U 'mineru[core]' --break-system-packages && \
    python3 -m pip cache purge

COPY requirements.txt .
RUN  pip install -r requirements.txt
# Stage 3: Download models and update configuration file

# Download models and update the configuration file
RUN /bin/bash -c "mineru-models-download -s huggingface -m all"

# Final Stage: Assemble the production image
FROM lmsysorg/sglang:v0.4.9.post6-cu126
WORKDIR /code

# Install only runtime dependencies if needed (or copy them from builder)
RUN apt-get update && apt-get install -y \
    libgl1 && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local /usr/local
COPY --from=builder /root/.cache /root/.cache

COPY . .

EXPOSE 8000
ENTRYPOINT ["/bin/bash", "-c", "export MINERU_MODEL_SOURCE=local && exec \"$@\"", "--"]
CMD ["gunicorn", "app:app"]