FROM python:3.10-slim

WORKDIR /code

COPY requirements.txt .


RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 8000

ENTRYPOINT ["gunicorn", "app:app", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]