FROM python:3.10-slim

WORKDIR /app

RUN pip3 install streamlit requests python-dotenv

COPY frontend_app.py .

EXPOSE 8501

ENTRYPOINT ["streamlit", "run", "frontend_app.py", "--server.port=8501", "--server.address=0.0.0.0"]